security:
    encoders:
        Labs\ApiBundle\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: Labs\ApiBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/api/accounts/ServiceClient
            stateless: true
            anonymous: true

        register_client:
            pattern:  ^/api/accounts/ServiceSeller
            stateless: true
            anonymous: true

        register_compagnay:
            pattern:  ^/api/accounts/ServiceCompagny
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/accounts/ServiceSeller, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/accounts/ServiceClient, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/accounts/ServiceCompagny, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
