# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    #listener authenticate success response

    api.event.authentication_success_listener:
        class: Labs\ApiBundle\Security\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    api.event.authentication_failure_listener:
        class: Labs\ApiBundle\Security\EventListener\AuthenticationFailureListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    api.event.jwt_invalid_listener:
        class: Labs\ApiBundle\Security\EventListener\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

    api.user_user_subscriber:
        class: Labs\ApiBundle\EventListener\UserSubscriber
        tags:
            - { name: kernel.event_subscriber }

    api.stock_event_subscriber:
        class: Labs\ApiBundle\EventListener\StockSubscriber
        tags:
            - { name: kernel.event_subscriber }

#Exception

    #app.exception_listener:
    #    class: Labs\ApiBundle\EventListener\ExceptionListener
    #    tags:
    #        - { name: kernel.event_listener, event: kernel.exception }

#Doctrine Events

    app.doctrine.hash_password_listener:
        class: Labs\ApiBundle\EventListener\Doctrine\HashPasswordListener
        tags:
            - { name: doctrine.event_subscriber }


    app.doctrine.cache_media_listener:
        class: Labs\ApiBundle\EventListener\Doctrine\CacheMediaListener
        arguments: ['@liip_imagine.cache.manager']
        tags:
            - { name: doctrine.event_listener, event: preRemove }


    app.doctrine.stock_subscriber:
        class: Labs\ApiBundle\EventSubscriber\Doctrine\StockLineSubscriber
        tags:
            - { name: doctrine.event_listener, event: prePersist }

#Handle

#Annotation Handler
    app.api_doc.annotation_handler:
        class: Labs\ApiBundle\AnnotationHandler\RestResultHandler
        arguments: ['@nelmio_api_doc.extractor.handler.fos_rest']
        tags:
            - { name: nelmio_api_doc.extractor.handler}
