<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository{

    public function getOneCategoryDepartment($department, $category)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.department', 'd');
        $qb->addSelect('d');
        $qb->where(
            $qb->expr()->eq('c.id', ':category'),
            $qb->expr()->eq('d.id',':department')
        );
        $qb->setParameter('category', $category);
        $qb->setParameter('department', $department);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
