<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

    public function getListQB()
    {
        $qb = $this->createQueryBuilder('c');
        return $qb;
    }

    /**
     * @param $country
     * @param $city
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getCityByCountryId($country, $city)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.id = :city');
        $qb->andWhere('c.country = :country');
        $qb->setParameter('city', $city);
        $qb->setParameter('country', $country);
        return $qb;
    }
}
