<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

    public function getOneCityCountry($country, $city){
        $qb = $this->createQueryBuilder('city');
        $qb->leftJoin('city.country', 'country');
        $qb->addSelect('country');
        $qb->where(
            $qb->expr()->eq('city.id', ':city'),
            $qb->expr()->eq('country.id',':country')
        );
        $qb->setParameter('country', $country);
        $qb->setParameter('city', $city);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
