<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends EntityRepository
{

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getListQB()
    {
        $qb = $this->createQueryBuilder('cmd');
        return $qb;
    }

    /**
     * @param $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getListWithParamsQB($user)
    {
        $qb = $this->createQueryBuilder('cmd');
        $qb->where($qb->expr()->eq('cmd.user', ':user'));
        $qb->setParameter('user', $user);
        return $qb;
    }

    /**
     * @param $user
     * @param $order
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getUserByOrderId($user, $order){

        $qb = $this->createQueryBuilder('cmd');
        $qb->where('cmd.id = :order');
        $qb->andWhere('cmd.user = :user');
        $qb->setParameter('order', $order);
        $qb->setParameter('user', $user);
        return $qb;
    }
}
