<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    public function getListQB(){
        $qb = $this->createQueryBuilder('n');
        return $qb;
    }

    /**
     * @param $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getListWithParamsQB($user)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where($qb->expr()->eq('n.user', ':user'));
        $qb->setParameter('user', $user);
        return $qb;
    }

    /**
     * @param $user
     * @param null $notification
     * @return \Doctrine\ORM\QueryBuilder
     * (Get One Notification or many Notifications)
     */
    public function getNotificationByUserAuthenticated($user, $notification = null)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.user = :user');
        if ($notification !== null){
            $qb->andWhere('n.id = :notification');
            $qb->setParameter('notification', $notification);
        }
        $qb->setParameter('user', $user);
        return $qb;
    }
}
