<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function getListQB()
    {
        $qb = $this->createQueryBuilder('p');
        return $qb;
    }

    public function getSectionStoreByProduct($section, $store, $product)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.id = :product');
        $qb->andWhere('p.section = :section');
        $qb->andWhere('p.store = :store');
        $qb->setParameter('product', $product);
        $qb->setParameter('section', $section);
        $qb->setParameter('store', $store);
        return $qb;
    }
}
