<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository
{

    public function getListQB()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb;
    }

    public function getSectionByCategory($category, $section)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.id = :section');
        $qb->andWhere('s.category = :category');
        $qb->setParameter('category', $category);
        $qb->setParameter('section', $section);
        return $qb;
    }
}
