<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends EntityRepository
{

    public function getListQB()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb;
    }

    public function getDepartmentStreetByStore($department, $street, $store)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('c.id = :store');
        $qb->andWhere('s.department = :department');
        $qb->andWhere('s.street = :street');
        $qb->setParameter('street', $street);
        $qb->setParameter('department', $department);
        $qb->setParameter('store', $store);
        return $qb;
    }
}
