<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends EntityRepository
{

    public function getListQB()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb;
    }

    public function getStreetByCity($city, $street)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.id = :street');
        $qb->andWhere('s.city = :city');
        $qb->setParameter('city', $city);
        $qb->setParameter('street', $street);
        return $qb;
    }
}
