<?php

namespace Labs\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getListQB()
    {
        $qb = $this->createQueryBuilder('u');
        return $qb;
    }


    public function findByField($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email OR u.phone = :phone')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->setParameter('phone', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
